apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: backstage
  namespace: backstage
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: backstage-secrets
    creationPolicy: Owner
    template:
      data:
        GITHUB_TOKEN: "{{ .GITHUB_TOKEN }}"
        AUTHENTIK_CLIENT_ID: "{{ .AUTHENTIK_CLIENT_ID }}"
        AUTHENTIK_CLIENT_SECRET: "{{ .AUTHENTIK_CLIENT_SECRET }}"
        APP_CONFIG_auth_providers_oidc_production_clientId: "{{ .AUTHENTIK_CLIENT_ID }}"
        APP_CONFIG_auth_providers_oidc_production_clientSecret: "{{ .AUTHENTIK_CLIENT_SECRET }}"
        APP_CONFIG_auth_providers_oidc_production_metadataUrl: "https://auth.in.hypyr.space/application/o/backstage/.well-known/openid-configuration"
        APP_CONFIG_integrations_github_0_host: "github.com"
        APP_CONFIG_integrations_github_0_token: "{{ .GITHUB_TOKEN }}"
  dataFrom:
    - extract:
        key: backstage
