services:
  uptime-kuma:
    image: louislam/uptime-kuma:1.23.13@sha256:96510915e6be539b76bcba2e6873591c67aca8a6075ff09f5b4723ae47f333fc
    restart: unless-stopped
    volumes:
      - /mnt/apps01/appdata/uptime-kuma:/app/data
    labels:
      caddy: status.in.hypyr.space
      caddy.reverse_proxy: "{{upstreams 3001}}"
    networks:
      - proxy_network

networks:
  proxy_network:
    external: true
