services:
  uptime-kuma:
    image: louislam/uptime-kuma:2.0.2@sha256:4c364ef96aaddac7ec4c85f5e5f31c3394d35f631381ccbbf93f18fd26ac7cba
    restart: unless-stopped
    volumes:
      - /mnt/apps01/appdata/uptime-kuma:/app/data
    labels:
      caddy: status.in.hypyr.space
      caddy.reverse_proxy: "{{upstreams 3001}}"
    networks:
      proxy_network:
        aliases:
          - uptime-kuma

networks:
  proxy_network:
    external: true
