apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: node-local
provisioner: rancher.io/local-path
parameters:
  path: /var/lib/local-path-provisioner
  nodePathType: DirectoryOrCreate
allowVolumeExpansion: false
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
mountOptions:
  - noatime
  - nodiratime
