apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/cilium
  - ../../components/coredns
  - ../../components/spegel
  - ../../components/cert-manager
  - ../../components/external-secrets
  - ../../components/onepassword-store
  - ../../components/kube-vip
patches: []
