apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: example-exception
  namespace: policy-exceptions
  annotations:
    policies.kyverno.io/exception: "approved-by: <approver> reason: <justification> expires: <date>"
spec:
  match:
    any:
      - resources:
          kinds:
            - Pod
  rules:
    - name: exempt-one-rule
      match:
        any:
          - resources:
              kinds:
                - Pod
      policyName: <policy-name>
      ruleNames:
        - <rule-name>
