apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-restic"
  namespace: ${NAMESPACE}
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-restic-secret"
    creationPolicy: Owner
    template:
      data:
        RESTIC_REPOSITORY: "{{ .RESTIC_REPOSITORY }}"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
        AWS_DEFAULT_REGION: "{{ .S3_REGION }}"
        RESTIC_S3_ENDPOINT: "{{ .S3_ENDPOINT }}"
  dataFrom:
    - extract:
        key: ${RESTIC_SECRET_KEY:=volsync-restic}
