apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}"
  namespace: ${NAMESPACE}
spec:
  trigger:
    manual: restore-once
  restic:
    repository: "${APP}-restic-secret"
    copyMethod: Snapshot
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:=s3-snapshot}"
    cacheStorageClassName: "${VOLSYNC_CACHE_SNAPSHOTCLASS:=node-local}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}"]
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=2Gi}"
    storageClassName: "${VOLSYNC_STORAGECLASS:=longhorn-replicated}"
    accessModes: ["${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"]
    capacity: "${VOLSYNC_CAPACITY:=5Gi}"
    moverSecurityContext:
      runAsUser: "${VOLSYNC_PUID:=1701}"
      runAsGroup: "${VOLSYNC_PGID:=1702}"
      fsGroup: "${VOLSYNC_PGID:=1702}"
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
