apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}"
  namespace: ${NAMESPACE}
spec:
  sourcePVC: "${PVC}"
  trigger:
    schedule: "${VOLSYNC_SCHEDULE:=15 */8 * * *}"
  restic:
    copyMethod: "${VOLSYNC_COPYMETHOD:=Snapshot}"
    pruneIntervalDays: 14
    repository: "${APP}-restic-secret"
    volumeSnapshotClassName: "${VOLSYNC_SNAPSHOTCLASS:=s3-snapshot}"
    cacheCapacity: "${VOLSYNC_CACHE_CAPACITY:=2Gi}"
    cacheStorageClassName: "${VOLSYNC_CACHE_STORAGECLASS:=node-local}"
    cacheAccessModes: ["${VOLSYNC_CACHE_ACCESSMODES:=ReadWriteOnce}"]
    storageClassName: "${VOLSYNC_STORAGECLASS:=longhorn-replicated}"
    accessModes: ["${VOLSYNC_SNAP_ACCESSMODES:=ReadWriteOnce}"]
    moverSecurityContext:
      runAsUser: "${VOLSYNC_PUID:=1701}"
      runAsGroup: "${VOLSYNC_PGID:=1702}"
      fsGroup: "${VOLSYNC_PGID:=1701}"
    retain:
      hourly: 24
      daily: 7
