apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - https://github.com/backube/volsync/releases/download/v0.9.0/volsync-bundle.yaml
  - restic-externalsecret.yaml
components:
  - templates
