apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: volsync-restic
  namespace: volsync-system
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: volsync-restic
    creationPolicy: Owner
  data:
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: volsync-restic
        property: RESTIC_REPOSITORY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: volsync-restic
        property: RESTIC_PASSWORD
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: volsync-restic
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: volsync-restic
        property: AWS_SECRET_ACCESS_KEY
    - secretKey: AWS_DEFAULT_REGION
      remoteRef:
        key: volsync-restic
        property: AWS_DEFAULT_REGION
    - secretKey: RESTIC_S3_ENDPOINT
      remoteRef:
        key: volsync-restic
        property: RESTIC_S3_ENDPOINT
    - secretKey: RESTIC_S3_BUCKET
      remoteRef:
        key: volsync-restic
        property: RESTIC_S3_BUCKET
