apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loki-restic
  namespace: observability
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: loki-restic-secret
    creationPolicy: Owner
    template:
      data:
        RESTIC_REPOSITORY: "{{ .RESTIC_REPOSITORY }}"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
        AWS_DEFAULT_REGION: "{{ .S3_REGION }}"
        RESTIC_S3_ENDPOINT: "{{ .S3_ENDPOINT }}"
  dataFrom:
    - extract:
        key: volsync-restic
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: loki
  namespace: observability
spec:
  sourcePVC: storage-loki-singlebinary-0
  trigger:
    schedule: "0 */6 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: loki-restic-secret
    volumeSnapshotClassName: s3-snapshot
    cacheCapacity: 5Gi
    cacheStorageClassName: node-local
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: longhorn-replicated
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      hourly: 24
      daily: 7
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: loki
  namespace: observability
spec:
  trigger:
    manual: restore-once
  restic:
    repository: loki-restic-secret
    copyMethod: Snapshot
    volumeSnapshotClassName: s3-snapshot
    cacheStorageClassName: node-local
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: 5Gi
    storageClassName: longhorn-replicated
    accessModes: ["ReadWriteOnce"]
    capacity: 50Gi
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
