---
all:
  children:
    managers:
      hosts:
        ching:
          ansible_host: 10.0.5.93
        angre:
          ansible_host: 10.0.5.130
    workers:
      hosts:
        lorcha:
          ansible_host: 10.0.5.215
        dhow:
          ansible_host: 10.0.5.220
    swarm_nodes:
      children:
        managers:
        workers:
  vars:
    ansible_user: deploy
    ansible_become: true
