apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-system/metrics-server
  - kube-system/reloader
  - kube-system/descheduler
  - observability
  - networking
patches: []
