apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - kube-system/metrics-server
  - kube-system/reloader
  - kube-system/descheduler
  - observability
  - networking
  - default
  - actions-runner-system
  - system-upgrade
  - volsync-system
  - cert-manager
  - databases
  - media
patches: []
