apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ocirepo.yaml
  - externalsecret.yaml
  - prometheusrule.yaml
  - helmrelease.yaml
  - longhorn.rules.yaml
  - volsync.rules.yaml
  - servicemonitor-longhorn.yaml
  - servicemonitor-volsync.yaml
  - volsync.yaml
