apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: volsync
  namespace: observability
spec:
  namespaceSelector:
    matchNames:
      - volsync-system
  selector:
    matchLabels:
      app.kubernetes.io/name: volsync
  endpoints:
    - port: http-metrics
      interval: 30s
      path: /metrics
