apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: prometheus-restic
  namespace: observability
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: prometheus-restic-secret
    creationPolicy: Owner
    template:
      data:
        RESTIC_REPOSITORY: "{{ .RESTIC_REPOSITORY }}"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
        AWS_DEFAULT_REGION: "{{ .S3_REGION }}"
        RESTIC_S3_ENDPOINT: "{{ .S3_ENDPOINT }}"
  dataFrom:
    - extract:
        key: volsync-restic
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: alertmanager-restic
  namespace: observability
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: alertmanager-restic-secret
    creationPolicy: Owner
    template:
      data:
        RESTIC_REPOSITORY: "{{ .RESTIC_REPOSITORY }}"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .S3_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .S3_SECRET_ACCESS_KEY }}"
        AWS_DEFAULT_REGION: "{{ .S3_REGION }}"
        RESTIC_S3_ENDPOINT: "{{ .S3_ENDPOINT }}"
  dataFrom:
    - extract:
        key: volsync-restic
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: prometheus
  namespace: observability
spec:
  sourcePVC: prometheus-data
  trigger:
    schedule: "5 */6 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: prometheus-restic-secret
    volumeSnapshotClassName: s3-snapshot
    cacheCapacity: 5Gi
    cacheStorageClassName: node-local
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: longhorn-replicated
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
    retain:
      hourly: 24
      daily: 7
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: prometheus
  namespace: observability
spec:
  trigger:
    manual: restore-once
  restic:
    repository: prometheus-restic-secret
    copyMethod: Snapshot
    volumeSnapshotClassName: s3-snapshot
    cacheStorageClassName: node-local
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: 5Gi
    storageClassName: longhorn-replicated
    accessModes: ["ReadWriteOnce"]
    capacity: 50Gi
    moverSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: alertmanager
  namespace: observability
spec:
  sourcePVC: alertmanager-data
  trigger:
    schedule: "35 */8 * * *"
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 14
    repository: alertmanager-restic-secret
    volumeSnapshotClassName: s3-snapshot
    cacheCapacity: 2Gi
    cacheStorageClassName: node-local
    cacheAccessModes: ["ReadWriteOnce"]
    storageClassName: longhorn-replicated
    accessModes: ["ReadWriteOnce"]
    moverSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
    retain:
      hourly: 24
      daily: 7
---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: alertmanager
  namespace: observability
spec:
  trigger:
    manual: restore-once
  restic:
    repository: alertmanager-restic-secret
    copyMethod: Snapshot
    volumeSnapshotClassName: s3-snapshot
    cacheStorageClassName: node-local
    cacheAccessModes: ["ReadWriteOnce"]
    cacheCapacity: 2Gi
    storageClassName: longhorn-replicated
    accessModes: ["ReadWriteOnce"]
    capacity: 1Gi
    moverSecurityContext:
      runAsUser: 65534
      runAsGroup: 65534
      fsGroup: 65534
    enableFileDeletion: true
    cleanupCachePVC: true
    cleanupTempPVC: true
