apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - ocirepo.yaml
  - helmrelease.yaml
configMapGenerator:
  - name: alloy-configmap
    files:
      - config.alloy=./resources/config.alloy
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
