apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab-root
  path: ./kubernetes/clusters/homelab/platform
  retryInterval: 1m
