apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: onepassword-store
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab-root
  path: ./kubernetes/components/onepassword-store
  retryInterval: 1m
