apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: policies
  namespace: flux-system
spec:
  dependsOn:
    - name: kyverno
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: homelab-root
  path: ./kubernetes/policies
  retryInterval: 1m
