apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  healthChecks:
    - apiVersion: v1
      kind: Secret
      name: onepassword-secret
      namespace: external-secrets
    - apiVersion: external-secrets.io/v1
      kind: ClusterSecretStore
      name: onepassword
      namespace: external-secrets
  sourceRef:
    kind: GitRepository
    name: homelab-root
  path: ./kubernetes/components/external-secrets
  retryInterval: 1m
