apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: platform
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
    - name: onepassword-store
    - name: kyverno
    - name: policies
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  healthChecks:
    - apiVersion: external-secrets.io/v1
      kind: ClusterSecretStore
      name: onepassword
      namespace: external-secrets
  sourceRef:
    kind: GitRepository
    name: homelab-root
  path: ./kubernetes/clusters/homelab/platform
  retryInterval: 1m
