apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: kyverno
  namespace: flux-system
spec:
  dependsOn:
    - name: external-secrets
    - name: onepassword-store
  interval: 10m
  timeout: 5m
  prune: true
  wait: true
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: kyverno
      namespace: kyverno
  sourceRef:
    kind: GitRepository
    name: homelab-root
  path: ./kubernetes/components/kyverno
  retryInterval: 1m
