tunnel: ${TUNNEL_ID}
credentials-file: /secrets/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true

ingress:
  - hostname: "*.hypyr.space"
    service: https://caddy:443
    originRequest:
      noTLSVerify: true
  - hostname: "*.in.hypyr.space"
    service: https://caddy:443
    originRequest:
      noTLSVerify: true
  - service: http_status:404
