tunnel: {{ op://homelab/cloudflare-tunnel/tunnel_id }}
credentials-file: /secrets/credentials.json
metrics: 0.0.0.0:2000
no-autoupdate: true

ingress:
  - hostname: "*.hypyr.space"
    service: http://caddy:80
  - hostname: "*.in.hypyr.space"
    service: http://caddy:80
  - service: http_status:404
