apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: atuin
  namespace: default
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: atuin-secret
    creationPolicy: Owner
  data:
    - secretKey: ATUIN_DB_KEY
      remoteRef:
        key: atuin
        property: ATUIN_DB_KEY
    - secretKey: ATUIN_PUBLIC_KEY
      remoteRef:
        key: atuin
        property: ATUIN_PUBLIC_KEY
    - secretKey: ATUIN_PRIVATE_KEY
      remoteRef:
        key: atuin
        property: ATUIN_PRIVATE_KEY
