apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - keda
  - kube-prometheus-stack
  - loki
  - grafana
  - blackbox-exporter
  - gatus
  - karma
  - smartctl-exporter
  - unpoller
  - alloy
  - snmp-exporter
  - silence-operator
  - kromgo
