---
roles:
  - name: geerlingguy.docker
    version: "7.4.1"

collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=9.0.0"
  - name: devsec.hardening
    version: ">=10.1.0"
