apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ingress/deny-loadbalancer-external-ips.yaml
  - ingress/deny-nodeport-services.yaml
  - secrets/deny-inline-secrets.yaml
  - secrets/guard-onepassword-bootstrap-secret.yaml
  - secrets/require-allowed-secret-store.yaml
  - secrets/require-external-secrets-operator.yaml
  - storage/deny-database-on-longhorn.yaml
  - storage/deny-node-local-for-critical-data.yaml
  - storage/enforce-longhorn-replicas.yaml
  - storage/limit-volume-size.yaml
  - storage/require-volsync-for-annotated-pvc.yaml
  - storage/restrict-rwx-access-mode.yaml
