apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: observability
resources:
  - externalsecret.yaml
  - rbac.yaml
  - prometheusrule.yaml
  - helmrelease.yaml
components:
  - ../../../../../components/gatus
configMapGenerator:
  - name: gatus-configmap
    files:
      - ./resources/config.yaml
generatorOptions:
  disableNameSuffixHash: true
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
