apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: gatus
  namespace: observability
spec:
  groups:
    - name: gatus
      rules:
        - alert: GatusEndpointFailure
          expr: gatus_result_total{success="false"} > 0
          for: 5m
          labels:
            severity: warning
          annotations:
            summary: Gatus endpoint failures detected
            description: "One or more Gatus checks are failing."
